# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(559, 494)
        MainWindow.setStyleSheet("background-color: rgb(230, 32, 84);\n"
"background-color: rgb(230, 230, 230);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 80, 501, 401))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn1.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.btn1.setObjectName("btn1")
        self.gridLayout.addWidget(self.btn1, 7, 0, 1, 1)
        self.btn4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn4.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.btn4.setObjectName("btn4")
        self.gridLayout.addWidget(self.btn4, 6, 0, 1, 1)
        self.btn5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn5.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.btn5.setObjectName("btn5")
        self.gridLayout.addWidget(self.btn5, 6, 1, 1, 1)
        self.btn3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.btn3.setObjectName("btn3")
        self.gridLayout.addWidget(self.btn3, 7, 2, 1, 1)
        self.btn2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.btn2.setObjectName("btn2")
        self.gridLayout.addWidget(self.btn2, 7, 1, 1, 1)
        self.btn7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn7.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.btn7.setObjectName("btn7")
        self.gridLayout.addWidget(self.btn7, 5, 0, 1, 1)
        self.btn8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn8.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.btn8.setObjectName("btn8")
        self.gridLayout.addWidget(self.btn8, 5, 1, 1, 1)
        self.btn9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn9.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.btn9.setObjectName("btn9")
        self.gridLayout.addWidget(self.btn9, 5, 2, 1, 1)
        self.btn6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn6.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.btn6.setObjectName("btn6")
        self.gridLayout.addWidget(self.btn6, 6, 2, 1, 1)
        self.btnsquare = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnsquare.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.btnsquare.setObjectName("btnsquare")
        self.gridLayout.addWidget(self.btnsquare, 1, 0, 1, 1)
        self.btncube = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btncube.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.btncube.setObjectName("btncube")
        self.gridLayout.addWidget(self.btncube, 1, 1, 1, 1)
        self.btnequal = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnequal.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.btnequal.setObjectName("btnequal")
        self.gridLayout.addWidget(self.btnequal, 0, 0, 1, 1)
        self.btnminus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnminus.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.btnminus.setObjectName("btnminus")
        self.gridLayout.addWidget(self.btnminus, 1, 2, 1, 1)
        self.btndel = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btndel.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.btndel.setObjectName("btndel")
        self.gridLayout.addWidget(self.btndel, 0, 1, 1, 1)
        self.btnclear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnclear.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.btnclear.setObjectName("btnclear")
        self.gridLayout.addWidget(self.btnclear, 0, 2, 1, 1)
        self.btnmulti = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnmulti.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.btnmulti.setObjectName("btnmulti")
        self.gridLayout.addWidget(self.btnmulti, 0, 3, 1, 1)
        self.btndiv = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btndiv.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.btndiv.setObjectName("btndiv")
        self.gridLayout.addWidget(self.btndiv, 1, 3, 1, 1)
        self.btnplus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnplus.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.btnplus.setObjectName("btnplus")
        self.gridLayout.addWidget(self.btnplus, 5, 3, 1, 1)
        self.btn0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn0.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.btn0.setObjectName("btn0")
        self.gridLayout.addWidget(self.btn0, 6, 3, 1, 1)
        self.btndot = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btndot.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.btndot.setObjectName("btndot")
        self.gridLayout.addWidget(self.btndot, 7, 3, 1, 1)
        self.inputLabel = QtWidgets.QLineEdit(self.centralwidget)
        self.inputLabel.setGeometry(QtCore.QRect(50, 30, 501, 51))
        self.inputLabel.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.inputLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.inputLabel.setObjectName("inputLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 559, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btn0.clicked.connect(self.method0)
        self.btn1.clicked.connect(self.method1)
        self.btn2.clicked.connect(self.method2)
        self.btn3.clicked.connect(self.method3)
        self.btn4.clicked.connect(self.method4)
        self.btn5.clicked.connect(self.method5)
        self.btn6.clicked.connect(self.method6)
        self.btn7.clicked.connect(self.method7)
        self.btn8.clicked.connect(self.method8)
        self.btn9.clicked.connect(self.method9)
        self.btndel.clicked.connect(self.methoddel)
        self.btnclear.clicked.connect(self.methodclear)
        self.btnsquare.clicked.connect(self.methodsquare)
        self.btncube.clicked.connect(self.methodcube)
        self.btnminus.clicked.connect(self.methodminus)
        self.btnmulti.clicked.connect(self.methodmulti)
        self.btndiv.clicked.connect(self.methoddiv)
        self.btnplus.clicked.connect(self.methodplus)
        self.btnequal.clicked.connect(self.methodequal)
        self.btndot.clicked.connect(self.methoddot)


    def method0(self):
        entry=self.inputLabel.text()
        self.inputLabel.setText(entry+ "0")
    def method1(self):
        entry=self.inputLabel.text()
        self.inputLabel.setText(entry+ "1")
    def method2(self):
        entry=self.inputLabel.text()
        self.inputLabel.setText(entry+ "2")
    def method3(self):
        entry=self.inputLabel.text()
        self.inputLabel.setText(entry+ "3")
    def method4(self):
        entry=self.inputLabel.text()
        self.inputLabel.setText(entry+ "4")
    def method5(self):
        entry=self.inputLabel.text()
        self.inputLabel.setText(entry+ "5")
    def method6(self):
        entry=self.inputLabel.text()
        self.inputLabel.setText(entry+ "6")
    def method7(self):
        entry=self.inputLabel.text()
        self.inputLabel.setText(entry+ "7")
    def method8(self):
        entry=self.inputLabel.text()
        self.inputLabel.setText(entry+ "8")
    def method9(self):
        entry=self.inputLabel.text()
        self.inputLabel.setText(entry+ "9")
    def methodpercent(self):
        entry=self.inputLabel.text()
        self.inputLabel.setText(entry+ "%")
    def methoddot(self):
        entry=self.inputLabel.text()
        self.inputLabel.setText(entry+ ".")
    def methodplus(self):
        entry=self.inputLabel.text()
        self.inputLabel.setText(entry+ "+")
    def methodminus(self):
        entry=self.inputLabel.text()
        self.inputLabel.setText(entry+ "-")
    def methodmulti(self):
        entry=self.inputLabel.text()
        self.inputLabel.setText(entry+ "*")
    def methoddiv(self):
        entry=self.inputLabel.text()
        self.inputLabel.setText(entry+ "/")
    def methodplusminus(self):
        entry=self.inputLabel.text()
        self.inputLabel.setText(entry+ "+/-")
    def methoddel(self):
        entry=self.inputLabel.text()
        self.inputLabel.setText(entry[:len(entry)-1])
    
    def methodequal(self):
         entry=self.inputLabel.text()
         try:
             ans=eval(entry)
             self.inputLabel.setText(str(ans))
         except:
            self.inputLabel.setText("Error")
            
    def methodclear(self):
        entry=self.inputLabel.text()
        self.inputLabel.setText("")
        
    def methodsquare(self):
        entry=self.inputLabel.text()
        self.an=int(eval(entry)**2)
        self.inputLabel.setText(str(self.an))
        
    def methodcube(self):
        entry=self.inputLabel.text()
        self.an=int(eval(eval(entry)**3))
        self.inputLabel.setText(str(self.an))
        
         

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator app"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btnsquare.setText(_translate("MainWindow", "X^2"))
        self.btncube.setText(_translate("MainWindow", "X^3"))
        self.btnequal.setText(_translate("MainWindow", "="))
        self.btnminus.setText(_translate("MainWindow", "-"))
        self.btndel.setText(_translate("MainWindow", "Del"))
        self.btnclear.setText(_translate("MainWindow", "C"))
        self.btnmulti.setText(_translate("MainWindow", "x"))
        self.btndiv.setText(_translate("MainWindow", "÷"))
        self.btnplus.setText(_translate("MainWindow", "+"))
        self.btn0.setText(_translate("MainWindow", "0"))
        self.btndot.setText(_translate("MainWindow", "."))
        self.inputLabel.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
